# Release pipeline:
# 
# This pipeline triggers the cloud-based benchmarking workflow
# upon pushes to the dev environment. The benchmarking workflow 
# infrastructure code can be found in the following repository:
# https://github.com/geoschem/gc-cloud-infrastructure
#
# This pipeline is triggered by pushes to dev
#
# Notes:
#   - This workflow requires aws credentials necessary to
#     trigger the benchmarking step function via the aws cli. 
#     The credentials need step function permissions and can 
#     be added to the repo as an action secret called 
#     AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID.

name: cloud_benchmarking
on:
  push:
    branches:
      - feature/cloud-benchmarking-workflow

jobs:
  trigger_step_function:
    runs-on: ubuntu-latest # aws cli comes pre-installed
    steps:
      - name: Set Time Period
        run: |
          echo "TIME_PERIOD=1Mon" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      - name: Set Time Period
        run: |
          echo "TIME_PERIOD=1Day" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/heads/')
      - name: Trigger Step Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_DEFAULT_OUTPUT: json

        # Note the step function input is sent in as a single json string
        run: |
          export WORKFLOW_ARN=$(aws stepfunctions list-state-machines \
            --output text \
            --query 'stateMachines[?name==`benchmarks-cloud-workflow`].stateMachineArn | [0]')
          aws stepfunctions start-execution \
            --state-machine-arn ${WORKFLOW_ARN} \
            --input "{\"event\": {"`
                `"\"nameSuffix\": \"${GITHUB_SHA}\","`
                `"\"simulationType\": \"GCC\","`
                `"\"runType\": \"SPOT\","`
                `"\"timePeriod\": \"${TIME_PERIOD}\","`
                `"\"tag\": \"${GITHUB_SHA}\","`
                `"\"numCores\": \"48\","`
                `"\"memory\": \"16000\","` 
                `"\"resolution\": \"24\","`
                `"\"sendEmailNotification\": \"true\","`
                `"\"updateInputData\": \"0\""`
              `"}}"
      