#
# GitHub Actions configuration file to perform "compile-only"
# integration tests for GEOS-Chem Classic that are triggered by
# push or pull requests.
#
name: gcclassic-compile-tests

on: [pull_request, push]

# Cancel running jobs if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug]
        gcc-version: [10, 11, 12, 13, 14, 15, 16]
    env:
      CXX: g++
      CC: gcc
      FC: gfortran

    name: Compile-only tests (${{ matrix.build_type }}, GCC ${{ matrix.gcc-version }})
    steps:
      - name: Checkout code
        with:
          persist-credentials: false
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo grep -rl 'packages.microsoft.com' /etc/apt/sources.list.d/ | xargs -r sudo rm -f
          sudo apt update -y
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt update -y
          sudo apt install -y gcc-${{ matrix.gcc-version }} g++-${{ matrix.gcc-version }} gfortran-${{ matrix.gcc-version }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ matrix.gcc-version }} 100 \
             --slave /usr/bin/g++ g++ /usr/bin/g++-${{ matrix.gcc-version }} \
             --slave /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ matrix.gcc-version }}
          sudo apt install -y libnetcdf-dev netcdf-bin libnetcdff-dev

      - name: Verify environment
        run: |
          gcc --version
          g++ --version
          gfortran --version

      - name: Compile-only tests
        run: |
          git submodule update --init --recursive
          cd test/integration/GCClassic
          ./integrationTest.sh -d $HOME/compile-tests -t compile
          cat $HOME/compile-tests/logs/results.compile.log
