#
# GitHub Actions configuration file to perform "compile-only"
# integration tests for GEOS-Chem Classic that are triggered by
# push or pull requests.
#
name: gcclassic-compile-tests

on: [pull_request, push]

# Cancel running jobs if new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gnu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug]
    env:
      CXX: g++
      CC: gcc
      FC: gfortran

    steps:
      - name: Checkout code
        with:
          persist-credentials: false
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y libnetcdf-dev netcdf-bin libnetcdff-dev

      - name: Compile-only tests
        run: |
          git submodule update --init --recursive
          cd test/integration/GCClassic
          ./integrationTest.sh -d $HOME/compile-tests -t compile
          cat $HOME/compile-tests/logs/results.compile.log
